### ISSUE TITLE
Should LICENSE be MIT/Apache2?

### ISSUE THREAD

**Issue by petertodd** [opentimestamps/rust-opentimestamps#2]
This seems to be the standard in Rust, and may make life a little easier for legal in some organizations if we use license conditions that they've already reviewed for other Rust projects.

Normally I advocate for GPL, but I think we can make a good case here that we want to prioritize adoption of the OpenTimestamps standard over anything else (it's such a simple standard anyway).

**Comment by apoelstra** [comment]
As the original author, I'm perfectly OK if the library is relicensed to Apache2 or MIT.

(Of course, the existing CC0 license lets you do this regardless of my feelings, but it's good to be clear that there is no contention happening.)

**Comment by casey-bowman** [comment]
Given that the rust client library here is already in the public domain (with its CC0 1.0 Universal license), is the question actually about the licensing of openstamps in general, including opentimestamps-server?

**Comment by petertodd** [comment]
No, I just mean rust-opentimestamps

The problem is CC0 1.0 Universal may cause legal barriers even though it *should* be more permissive than the standard Rust licenses.

**Comment by casey-bowman** [comment]
I see :)  just because that's the norm

**Comment by petertodd** [comment]
Changed: https://github.com/opentimestamps/rust-opentimestamps/pull/4
