### ISSUE TITLE
You service is sh*t for Bitcoin community :-E

### ISSUE THREAD

**Issue by Perlover** [opentimestamps/rust-opentimestamps#3]
Hi,

You service is sh*t for Bitcoin community :-E
You use UTXO for proof and a database of UTXO permanently grows from your proof transactions!
You could use OP_RETURN as it do https://proofofexistence.com/

It's right way!

**Comment by apoelstra** [comment]
Hi, no, opentimestamps timestamps have zero marginal space or verification cost to verifiers of the bitcoin network. I don't know what your service is but it's sure not below zero in terms of resource costs. Cheers.
